pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven { url = 'https://maven.parchmentmc.org' }
    }
}

// Optional toolchain resolver plugin.
// Disabled because plugins.gradle.org may be unreachable in some networks.
